### ISSUE TITLE
Reasoning should be false by default, not None

### ISSUE THREAD

**Issue by jgeluk** [modelfabric/reactive-sparql#18]
https://github.com/modelfabric/reactive-sparql/blob/e3ec7c08c56cea0b9d01fb979dd1a4483b0d8c1e/src/main/scala/com/modelfabric/sparql/api/SparqlQuery.scala#L63

**Comment by szaniszlo** [comment]
The client supports arbitrary SPARQL endpoints. The fact that you can, but are not required to pass the "reasoning=[true/false]" query parameter in the outbound HTTP request is modelled through the use of this Option[Boolean]. Basically the same thing as with "offset" and "limit" parameters.

Some endpoints may treat the non-existence of the "reasoning" parameter with a different default behaviour. We want to leave that option open to anybody using this library.

Leaving default to "None" means, don't tell the HTTP endpoint what kind of reasoning you want. Let the endpoint behave according to it's internal default behaviour. I believe in Stardog this would mean to run the query with the reasoner off.
